configfile: "benchmarking/config/config.yaml"


pepfile: config["pepfile"]


include: "rules/benchmarking.smk"


rule all:
    input:
        expand(
            "results/benchmarking/plots/variant-calls/precision-recall.source-{source}.cov-{cov}.svg",
            source=["stratified"],
            cov=["low", "high"],
        ),
        # "results/benchmarking/.saved",
        # "results/benchmarking/workflow-comparison-varaints.svg",
        # "results/benchmarking/workflow-comparison-mismatches.svg",
        # "results/benchmarking/plots/pangolin.svg",
        # "results/benchmarking/plots/time.svg",
        # "results/benchmarking/tabels/quast-sequences.tsv"
